#!/usr/bin/env sh

set -e

node --harmony-proxies node_modules/.bin/istanbul cover -x runtime.js _mocha -- -R spec --recursive --exit

if [ ! -z "$EXPORT_COVERAGE" ]; then
	cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

	rm -rf ./coverage
fi

